---
- name: Deploy Web & Cloudflare Tunnel on AWS
  hosts: aws
  become: yes
  vars:
    token: "{{ tunnel_token }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  tasks:
    - name: Install Nginx (AWS)
      yum:
        name: nginx
        state: present

    - name: Set Web Page Content (AWS)
      shell: "echo '<h1>AWS (Sub) - /2</h1>' > /usr/share/nginx/html/index.html"

    - name: Start and Enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Download Cloudflared (RPM)
      get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
        dest: /tmp/cloudflared.rpm

    - name: Install Cloudflared
      yum:
        name: /tmp/cloudflared.rpm
        state: present
        disable_gpg_check: yes

    - name: Uninstall existing Cloudflared service (if any)
      shell: "cloudflared service uninstall"
      ignore_errors: yes

    - name: Install and Start Cloudflared Service
      shell: "cloudflared service install {{ token }}"
      args:
        # 이전에 설치된 서비스가 있더라도 무시하고 새로 설치하기 위해 creates 주석 처리
        # creates: /etc/systemd/system/cloudflared.service
      notify: Restart Cloudflared

  handlers:
    - name: Restart Cloudflared
      ansible.builtin.systemd:
        name: cloudflared
        state: restarted

- name: Deploy Web & Cloudflare Tunnel on GCP
  hosts: gcp
  become: yes
  vars:
    token: "{{ tunnel_token }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  tasks:
    - name: Install Nginx (GCP)
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Set Web Page Content (GCP)
      shell: "echo '<h1>GCP (Main) - /1</h1>' > /var/www/html/index.html"

    - name: Start and Enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Download Cloudflared (DEB)
      get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        dest: /tmp/cloudflared.deb

    - name: Install Cloudflared
      apt:
        deb: /tmp/cloudflared.deb
        state: present

    - name: Uninstall existing Cloudflared service (if any)
      shell: "cloudflared service uninstall"
      ignore_errors: yes

    - name: Install and Start Cloudflared Service
      shell: "cloudflared service install {{ token }}"
      # args:
      #   creates: /etc/systemd/system/cloudflared.service
      notify: Restart Cloudflared

  handlers:
    - name: Restart Cloudflared
      ansible.builtin.systemd:
        name: cloudflared
        state: restarted
